### ISSUE TITLE
Thermostat setting is reverting to set temperature

### ISSUE THREAD

**Issue by tigrrr** [dynasticorpheus/gigasetelements-ha#24]
The thermostat (model ONE X ) is reading the actual and set temperature perfectly, but chaging the set temperature is not working, approx. after 3 seconds after a change of the temperature it reverts back to the previously set temperature.

**Comment by dynasticorpheus** [comment]
@tigrrr I think it will actually end up setting / reflecting the correct temperature selected but because there is a delay of 2.5 to 15 minutes before it gets applied on the device itself it jumps back awaiting for it to happen. Let me think how to better handle this code wise.

edit: could also be that model ONE X has different device ID e.g. bs01.ts02 instead of bs01.ts01. Can you perhaps turn on debugging and share logs which also includes setting the temperature?

edit2: I only find traces of ts01 in the official app code so my best guess what is happening is my initial feedback

```
logger:
  default: warn
  logs:
    custom_components.gigasetelements: debug
```

**Comment by tigrrr** [comment]
@dynasticorpheus I retested using both UI options and you're right - setting of the target temperature is reacting kind of funny.

3 seconds after setting the target temp, the number goes from red to black. 3 seconds later, the black number reverts to the initial value. After some minutes, in most of the cases the target temperatures obtain the desired target temperatures.

**Comment by dynasticorpheus** [comment]
@tigrrr  Thanks planning to make this a bit better for next release.
