### ISSUE TITLE
Support for Gigaset GoBox

### ISSUE THREAD

**Issue by FusselTV** [dynasticorpheus/gigasetelements-ha#26]
Hey,

Thanks for working on getting Gigaset elements into Home Assistant. Any thoughts on adding support for the Gigaset GoBox too? It works with Gigaset elements as well. Having a call log could be really cool, especially for times when you're not home. Also, getting direct call notifications would be a neat feature.

Cheers, Christian

![image](https://github.com/dynasticorpheus/gigasetelements-ha/assets/89834718/e96eb0b4-415d-49b7-b48a-781cc4497abc)

![signal-2023-08-12-130256_002](https://github.com/dynasticorpheus/gigasetelements-ha/assets/89834718/392c2857-6a90-4d76-9b73-b2e0cba0eca1)

**Comment by dynasticorpheus** [comment]
@FusselTV  Happy to have a look but since I do not own gobox myself I wll need your help. Can you install below CLI and run with -E option and share the json file created? Ideally you run it when you have things like missed calls etc

[gigasetelements-cli](https://github.com/dynasticorpheus/gigasetelements-cli)
